In [1]:

import numpy as np 
import pandas as pd
import random
import multiprocessing as mp
from multiprocessing import Pool
from numba import jit


In [2]:
#Lets make some fake data so that I have something to work with and to serve as a sample for the others.
#yeah so turns out it is much easier to use the inbuilt np functions than to try and do it myself. woops. but now we have a csv file with with 10 mill entries that we can 
#use for the next step in the process. They will have the lables, 0,1,2,3 where 0 means no mev, 1 means low, 2 means medium and 3 means high. 

numofsamples = 10000

data = np.vstack(np.random.randint(0,4,numofsamples))
lables = np.vstack(np.arange(0,numofsamples,1))
gasfees = np.vstack(np.random.rand(numofsamples))
volitility = np.vstack(np.random.rand(numofsamples))

data = np.append(lables,data,axis=1)
data = np.append(data,gasfees,axis=1)
data = np.append(data,volitility,axis=1)


print(data)



[[0.00000000e+00 2.00000000e+00 8.75339849e-01 8.70496361e-01]
 [1.00000000e+00 0.00000000e+00 6.64251242e-01 9.95776649e-01]
 [2.00000000e+00 2.00000000e+00 5.17810565e-01 8.59385246e-01]
 ...
 [9.99700000e+03 1.00000000e+00 3.13720353e-01 7.07850871e-01]
 [9.99800000e+03 3.00000000e+00 5.12175624e-01 5.64553907e-01]
 [9.99900000e+03 3.00000000e+00 5.54034209e-02 3.86228289e-01]]


In [3]:
#Lastly we can save the data that has been created using this line. 

np.savetxt("../ethdata/randomdatawgv.csv",data,delimiter=",")