In [1]:

import numpy as np 
import pandas as pd
import random
import multiprocessing as mp
from multiprocessing import Pool
from numba import jit


In [2]:
#Lets make some fake data so that I have something to work with and to serve as a sample for the others.
#yeah so turns out it is much easier to use the inbuilt np functions than to try and do it myself. woops. but now we have a csv file with with 10 mill entries that we can 
#use for the next step in the process. They will have the lables, 0,1,2,3 where 0 means no mev, 1 means low, 2 means medium and 3 means high. 
#it will also include a number for the gas fees and the volitilty of the price of etherium as compared to USD, these are normalised numbers so will not be raw data going in.

numofsamples = 10000

data = np.vstack(np.random.randint(0,4,numofsamples))
lables = np.vstack(np.arange(0,numofsamples,1))
gasfees = np.vstack(np.random.rand(numofsamples))
volitility = np.vstack(np.random.rand(numofsamples))

data = np.append(lables,data,axis=1)
data = np.append(data,gasfees,axis=1)
data = np.append(data,volitility,axis=1)


print(data)



[[0.00000000e+00 0.00000000e+00 8.92528892e-01 2.00729663e-01]
 [1.00000000e+00 2.00000000e+00 6.72536093e-01 1.17525923e-02]
 [2.00000000e+00 2.00000000e+00 2.54252687e-01 8.75190263e-02]
 ...
 [9.99700000e+03 1.00000000e+00 1.10427486e-01 4.00522341e-01]
 [9.99800000e+03 0.00000000e+00 8.30791638e-02 1.69987927e-01]
 [9.99900000e+03 2.00000000e+00 2.69555288e-01 1.21179802e-01]]


In [3]:
#Lastly we can save the data that has been created using this line. 

np.savetxt("../ethdata/randomdatawgv.csv",data,delimiter=",")